var theme = {
    name: 'middag',

    audio: {},

    nebula: {
        mood: ['#00FF00', '#00FFFF'],
        diameter: 75
    },

    sprites: {
        planet: {
            'sprite-fili': [
                'fili-typen', 'trigger:sprite-signal:stop', 'fili-ossybot', 'trigger:sprite-ossy:stop',
                'trigger:sprite-signal:stop', 'fili-typen', 'fili-typen', 'trigger:sprite-signal:stop',
                'fili-energy', 'trigger:sprite-signal:stop', 'fili-typen-snel', 'trigger:sprite-signal:stop',
                'fili-typen', 'fili-typen', 'trigger:sprite-signal:stop',
                'fili-gebeld', 'trigger:sprite-signal:stop', 'fili-typen'
            ],
            'sprite-ossy': ['empty', 'ossybot-los', 'ossybot-los-zweef'],
            'sprite-signal': [
                'signal-normaal', 'empty', 'signal-normaal', 'empty',
                'signal-snel', 'signal-normaal', 'empty'
            ]
        }
    },

    animations: {
        'signal-normaal': {
            url: '//galaxy.fili.nl/images/anim/signal.png',
            run: -1,
            delay: 50,
            cols: 13,
            rows: 1,
            left: 313,
            bottom: 346,
            script: [
                {sprite: 1},
                {sprite: 2},
                {sprite: 3},
                {sprite: 4},
                {sprite: 5},
                {sprite: 6},
                {sprite: 7},
                {sprite: 8},
                {sprite: 9},
                {sprite: 10},
                {sprite: 11},
                {sprite: 12},
                {sprite: 13, delay: 2000}
            ]
        },
        'signal-snel': {
            url: '//galaxy.fili.nl/images/anim/signal.png',
            run: -1,
            delay: 30,
            cols: 13,
            rows: 1,
            bottom: 346,
            left: 313,
            script: [
                {sprite: 1},
                {sprite: 2},
                {sprite: 3},
                {sprite: 4},
                {sprite: 5},
                {sprite: 6},
                {sprite: 7},
                {sprite: 8},
                {sprite: 9},
                {sprite: 10},
                {sprite: 11},
                {sprite: 12},
                {sprite: 13, delay: 200}
            ]
        },
        'empty': {
            url: '//galaxy.fili.nl/images/anim/empty.png',
            run: 0,
            cols: 1,
            rows: 1
        },
        'ossybot-los': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_ossybot-los_S.png',
            run: 1,
            cols: 4,
            rows: 1,
            delay: 120,
            left: 246,
            bottom: 378,
            script: [
                {sprite: 1, left: 15},
                {sprite: 2, left: 15},
                {sprite: 3, left: 15},
                {sprite: 4, left: 15}
            ]
        },
        'ossybot-los-zweef': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_ossybot-loszweef_S.png',
            run: -1,
            cols: 4,
            rows: 1,
            delay: 120,
            left: 310,
            bottom: 378,
            outOfViewStop: true,
            script: [
                {sprite: 1, left: 15},
                {sprite: 2, left: 15},
                {sprite: 3, left: 15},
                {sprite: 4, left: 15}
            ]
        },
        ///////////

        'fili-typen': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_typzijkant_S.png',
            run: 15, // loopbaar
            cols: 5,
            rows: 1,
            delay: 100,
            left: 106,
            bottom: 378
        },

        'fili-typen-snel': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_typhyper_S.png',
            run: 30, // loopbaar
            cols: 5,
            rows: 1,
            delay: 25,
            left: 106,
            bottom: 378
        },

        'fili-ossybot': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_ossybot_S.png',
            run: 1,
            cols: 4,
            rows: 13,
            delay: 100,
            left: 106,
            bottom: 378,
            cutOffFrames: 2,
            script: [
                {sprite: 1},
                {sprite: 2},
                {sprite: 3},
                {sprite: 4},
                {sprite: 5},
                {sprite: 6},
                {sprite: 7},
                {sprite: 8},
                {sprite: 9},
                {sprite: 10},
                {sprite: 11},
                {sprite: 12},
                {sprite: 13},
                {sprite: 14},
                {sprite: 15},
                {sprite: 16},
                {sprite: 17},
                {sprite: 18},
                {sprite: 19},
                {sprite: 20},
                {sprite: 19},
                {sprite: 21},
                {sprite: 22},
                {sprite: 23},
                {sprite: 24},
                {sprite: 25},
                {sprite: 26},
                {sprite: 27},
                {sprite: 28, delay: 1000},
                {sprite: 29},
                {sprite: 30},
                {sprite: 31},
                {sprite: 32},
                {sprite: 33},
                {sprite: 34},
                {sprite: 35, delay: 800},
                {sprite: 36, delay: 800},
                {sprite: 35, delay: 800},
                {sprite: 36, delay: 800},
                {sprite: 37},
                {sprite: 38},
                {sprite: 39},
                {sprite: 40},
                {sprite: 41},
                {sprite: 42},
                {sprite: 43},
                {sprite: 44},
                {sprite: 45},
                {sprite: 46},
                {sprite: 47},
                {sprite: 48},
                {sprite: 49},
                {sprite: 50}
            ]
        },

        'fili-energy': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_energy_S.png',
            run: 1,
            cols: 5,
            rows: 13,
            delay: 100,
            left: 106,
            bottom: 378,
            script: [
                {sprite: 1},
                {sprite: 2},
                {sprite: 3},
                {sprite: 4},
                {sprite: 5},
                {sprite: 6},
                {sprite: 7},
                {sprite: 8},
                {sprite: 9},
                {sprite: 10},
                {sprite: 11},
                {sprite: 12},
                {sprite: 13},
                {sprite: 14},
                {sprite: 15},
                {sprite: 16},
                {sprite: 17},
                {sprite: 18},
                {sprite: 19},
                {sprite: 20},
                {sprite: 21},
                {sprite: 22},
                {sprite: 23},
                {sprite: 24},
                {sprite: 25},
                {sprite: 26},
                {sprite: 27},
                {sprite: 28},
                {sprite: 29},
                {sprite: 30},
                {sprite: 31},
                {sprite: 32},
                {sprite: 33},
                {sprite: 34},
                {sprite: 35, delay: 800},

                {sprite: 36},
                {sprite: 37},
                {sprite: 38, delay: 800},
                {sprite: 39},
                {sprite: 40, delay: 400},

                {sprite: 36},
                {sprite: 37},
                {sprite: 38, delay: 800},
                {sprite: 39},
                {sprite: 40, delay: 1000},

                {sprite: 41, delay: 400},
                {sprite: 40, delay: 400},

                {sprite: 36},
                {sprite: 37},
                {sprite: 38, delay: 800},
                {sprite: 39},
                {sprite: 40, delay: 2000},

                {sprite: 41, delay: 400},
                {sprite: 42, delay: 400},
                {sprite: 41, delay: 400},
                {sprite: 42, delay: 400},
                {sprite: 43},
                {sprite: 44, delay: 800},

                {sprite: 45, delay: 50},
                {sprite: 46, delay: 50},
                {sprite: 47, delay: 50},
                {sprite: 48, delay: 50},
                {sprite: 49, delay: 50},
                {sprite: 50, delay: 50},
                {sprite: 51, delay: 50},
                {sprite: 52, delay: 50},
                {sprite: 53, delay: 50},
                {sprite: 54, delay: 50},
                {sprite: 55, delay: 50},
                {sprite: 56, delay: 50},
                {sprite: 57, delay: 50},
                {sprite: 58, delay: 50},
                {sprite: 59, delay: 50},
                {sprite: 60, delay: 50},
                {sprite: 61, delay: 50},
                {sprite: 62, delay: 50},
                {sprite: 63, delay: 50},
                {sprite: 64, delay: 50},
                {sprite: 65, delay: 50}
            ]
        },

        'fili-gebeld': {
            url: '//galaxy.fili.nl/images/anim/middag/pxlfili_gebeld_S.png',
            run: 1,
            cols: 6,
            rows: 13,
            delay: 100,
            left: 106,
            bottom: 378,
            script: [
                {sprite: 1},
                {sprite: 2},
                {sprite: 3},
                {sprite: 4},
                {sprite: 5},
                {sprite: 6},
                {sprite: 7},
                {sprite: 8},
                {sprite: 9},
                {sprite: 10},
                {sprite: 11},
                {sprite: 12},
                {sprite: 13},
                {sprite: 14},
                {sprite: 15},
                {sprite: 16},
                {sprite: 17},
                {sprite: 18},
                {sprite: 19},
                {sprite: 20},
                {sprite: 21},
                {sprite: 22},
                {sprite: 23},
                {sprite: 24},
                {sprite: 25},
                {sprite: 26},
                {sprite: 27},
                {sprite: 28},
                {sprite: 29},
                {sprite: 30},
                {sprite: 28},
                {sprite: 27},
                {sprite: 26},
                {sprite: 31},
                {sprite: 32},
                {sprite: 33},
                {sprite: 34},
                {sprite: 33},
                {sprite: 34},
                {sprite: 33, delay: 2000},
                {sprite: 34},
                {sprite: 33},
                {sprite: 34},
                {sprite: 33},
                {sprite: 34},
                {sprite: 33},

                {sprite: 35},//
                {sprite: 36},
                {sprite: 35},
                {sprite: 36, delay: 3000},
                {sprite: 35},
                {sprite: 36},
                {sprite: 35},
                {sprite: 36},
                {sprite: 35},
                {sprite: 36, delay: 1000},
                {sprite: 37},
                {sprite: 38},
                {sprite: 39},
                {sprite: 40},
                {sprite: 41},
                {sprite: 42},
                {sprite: 43},
                {sprite: 44},
                {sprite: 45},
                {sprite: 46, delay: 2000},
                {sprite: 47},
                {sprite: 48},
                {sprite: 47},
                {sprite: 48},
                {sprite: 47},
                {sprite: 48, delay: 3000},
                {sprite: 49},
                {sprite: 50},
                {sprite: 51},
                {sprite: 52},
                {sprite: 53},
                {sprite: 54},
                {sprite: 55},
                {sprite: 56},
                {sprite: 57},
                {sprite: 58},

                {sprite: 35},//
                {sprite: 36},
                {sprite: 35},
                {sprite: 36},
                {sprite: 35},
                {sprite: 36},
                {sprite: 37},
                {sprite: 38},
                {sprite: 39},
                {sprite: 40},
                {sprite: 41},
                {sprite: 42},
                {sprite: 43},
                {sprite: 44},
                {sprite: 45},
                {sprite: 46},
                {sprite: 47},
                {sprite: 48},
                {sprite: 47},
                {sprite: 48},
                {sprite: 47},
                {sprite: 48},
                {sprite: 49},
                {sprite: 50},
                {sprite: 51},
                {sprite: 52},
                {sprite: 53},
                {sprite: 54},
                {sprite: 55},
                {sprite: 56},
                {sprite: 57},
                {sprite: 58},

                {sprite: 59},
                {sprite: 60},
                {sprite: 61},
                {sprite: 62},
                {sprite: 63},
                {sprite: 64},
                {sprite: 27},
                {sprite: 28},
                {sprite: 29},
                {sprite: 28},
                {sprite: 27},
                {sprite: 26},
                {sprite: 64},
                {sprite: 65},
                {sprite: 66},
                {sprite: 67},
                {sprite: 68},
                {sprite: 69},
                {sprite: 70},
                {sprite: 71},
                {sprite: 72},
                {sprite: 73},
                {sprite: 74},
                {sprite: 75}
            ]
        }
    }
};
